<?php

namespace Database\Seeders;

use App\Models\User;
use App\Models\WorkPost;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use App\Models\Prefecture;

class DemoWorkPostSeeder extends Seeder
{
    /**
     * デモ用の募集データを作成する
     */
    public function run(): void
    {
        $posts = [
            [
                'email' => 'kenta.sato@example.com',
                'title' => '平日朝にLaravel開発を一緒に黙々作業できる方',
                'body' => 'フルリモートでLaravel案件を進めています。朝の時間を有効活用したいので、平日朝にZoomやGoogle Meetで軽く挨拶してから黙々作業できる方を探しています。作業内容は違っても大丈夫です。最後に今日やったことを簡単に共有できると嬉しいです。',
                'purpose' => '黙々作業',
                'location_type' => 'online',
                'meeting_tool' => 'Google Meet',
                'prefecture' => '東京都',
                'start_at' => Carbon::now()->addDays(1)->setTime(8, 0),
                'end_at' => Carbon::now()->addDays(1)->setTime(10, 0),
                'time_zone' => 'morning',
                'max_participants' => 3,
                'status' => 1,
            ],
            [
                'email' => 'misaki.tanaka@example.com',
                'title' => 'Figma作業を一緒に進めるデザイナーさん募集',
                'body' => 'LPデザインやバナー制作を進める時間を作りたいです。お互いに作業内容を共有して、基本は黙々、必要があれば軽く相談できるような作業会にしたいです。デザイナー以外の方でも歓迎です。',
                'purpose' => 'デザイン相談',
                'location_type' => 'online',
                'meeting_tool' => 'Zoom',
                'prefecture' => '大阪府',
                'start_at' => Carbon::now()->addDays(2)->setTime(13, 0),
                'end_at' => Carbon::now()->addDays(2)->setTime(15, 0),
                'time_zone' => 'daytime',
                'max_participants' => 4,
                'status' => 1,
            ],
            [
                'email' => 'shota.suzuki@example.com',
                'title' => '夜にAPI設計・DB設計を進める作業仲間を募集',
                'body' => '受託案件のAPI設計やDB設計を進めています。夜の時間帯に集中して作業したいので、同じように開発作業をしている方とつながりたいです。Laravel、AWS、MySQL周りの話もできます。',
                'purpose' => '技術相談',
                'location_type' => 'online',
                'meeting_tool' => 'Discord',
                'prefecture' => '神奈川県',
                'start_at' => Carbon::now()->addDays(1)->setTime(21, 0),
                'end_at' => Carbon::now()->addDays(1)->setTime(23, 0),
                'time_zone' => 'night',
                'max_participants' => 3,
                'status' => 1,
            ],
            [
                'email' => 'yuki.takahashi@example.com',
                'title' => 'ライティング作業を一緒に進める黙々会',
                'body' => 'SEO記事の構成作成や本文執筆を進めます。一人だと集中が切れやすいため、同じように文章作成や資料作成をしている方と一緒に作業したいです。会話少なめで大丈夫です。',
                'purpose' => '黙々作業',
                'location_type' => 'online',
                'meeting_tool' => 'Google Meet',
                'prefecture' => '京都府',
                'start_at' => Carbon::now()->addDays(3)->setTime(10, 0),
                'end_at' => Carbon::now()->addDays(3)->setTime(12, 0),
                'time_zone' => 'morning',
                'max_participants' => 5,
                'status' => 1,
            ],
            [
                'email' => 'daisuke.ito@example.com',
                'title' => 'React / Next.js の個人開発を一緒に進めませんか',
                'body' => 'Next.jsで個人開発をしています。作業時間を固定したいので、平日夜に一緒に作業できる方を募集します。最初に今日やることを共有して、最後に進捗を共有する形を考えています。',
                'purpose' => '個人開発',
                'location_type' => 'online',
                'meeting_tool' => 'Discord',
                'prefecture' => '愛知県',
                'start_at' => Carbon::now()->addDays(2)->setTime(20, 0),
                'end_at' => Carbon::now()->addDays(2)->setTime(22, 0),
                'time_zone' => 'night',
                'max_participants' => 4,
                'status' => 1,
            ],
            [
                'email' => 'aya.yamamoto@example.com',
                'title' => 'SNS運用・広告改善の作業時間を一緒に確保したいです',
                'body' => 'SNS投稿の分析や広告改善の作業を進めます。マーケティング系の仕事をしている方、資料作成や分析作業をしたい方と一緒に作業できると嬉しいです。',
                'purpose' => '情報交換',
                'location_type' => 'online',
                'meeting_tool' => 'Zoom',
                'prefecture' => '福岡県',
                'start_at' => Carbon::now()->addDays(4)->setTime(14, 0),
                'end_at' => Carbon::now()->addDays(4)->setTime(16, 0),
                'time_zone' => 'daytime',
                'max_participants' => 4,
                'status' => 1,
            ],
            [
                'email' => 'takuya.nakamura@example.com',
                'title' => 'AWS・Docker周りの作業を進めるエンジニア作業会',
                'body' => 'AWS、Docker、GitHub Actions周りの構築作業を進めます。インフラ系の作業は一人だと詰まりやすいので、軽く相談できる作業仲間がいると嬉しいです。',
                'purpose' => '技術相談',
                'location_type' => 'online',
                'meeting_tool' => 'Google Meet',
                'prefecture' => '北海道',
                'start_at' => Carbon::now()->addDays(5)->setTime(9, 0),
                'end_at' => Carbon::now()->addDays(5)->setTime(11, 0),
                'time_zone' => 'morning',
                'max_participants' => 3,
                'status' => 1,
            ],
            [
                'email' => 'nana.kobayashi@example.com',
                'title' => 'UI改善・Figma作業を一緒に進めたいです',
                'body' => 'WebサービスのUI改善案をFigmaで作成します。最初に作業内容を共有して、基本は黙々、最後に軽く成果物を共有する流れで考えています。',
                'purpose' => 'デザイン相談',
                'location_type' => 'online',
                'meeting_tool' => 'Zoom',
                'prefecture' => '兵庫県',
                'start_at' => Carbon::now()->addDays(6)->setTime(15, 0),
                'end_at' => Carbon::now()->addDays(6)->setTime(17, 0),
                'time_zone' => 'daytime',
                'max_participants' => 4,
                'status' => 1,
            ],
            [
                'email' => 'naoki.kato@example.com',
                'title' => 'Laravel個人開発を継続するための夜作業会',
                'body' => '個人開発を継続するために、夜に作業時間を固定したいです。LaravelやPHPを触っている方、学習中の方も歓迎です。作業内容は自由です。',
                'purpose' => '個人開発',
                'location_type' => 'online',
                'meeting_tool' => 'Discord',
                'prefecture' => '奈良県',
                'start_at' => Carbon::now()->addDays(1)->setTime(22, 0),
                'end_at' => Carbon::now()->addDays(1)->setTime(23, 30),
                'time_zone' => 'night',
                'max_participants' => 5,
                'status' => 1,
            ],
            [
                'email' => 'mayu.yoshida@example.com',
                'title' => '動画編集を集中して進める午後の作業会',
                'body' => 'YouTube動画やショート動画の編集を進めます。編集作業、デザイン作業、ライティング作業など、集中して進めたい方ならどなたでも歓迎です。',
                'purpose' => '黙々作業',
                'location_type' => 'online',
                'meeting_tool' => 'Google Meet',
                'prefecture' => '宮城県',
                'start_at' => Carbon::now()->addDays(3)->setTime(13, 30),
                'end_at' => Carbon::now()->addDays(3)->setTime(16, 0),
                'time_zone' => 'daytime',
                'max_participants' => 4,
                'status' => 1,
            ],
            [
                'email' => 'yuta.matsumoto@example.com',
                'title' => '資料作成・タスク整理を一緒に進める会',
                'body' => 'Web制作案件の資料作成やタスク整理を進めます。ディレクター、PM、エンジニア、デザイナーなど、職種問わず作業時間を確保したい方と一緒に進めたいです。',
                'purpose' => '作業仲間探し',
                'location_type' => 'online',
                'meeting_tool' => 'Zoom',
                'prefecture' => '埼玉県',
                'start_at' => Carbon::now()->addDays(7)->setTime(10, 0),
                'end_at' => Carbon::now()->addDays(7)->setTime(12, 0),
                'time_zone' => 'morning',
                'max_participants' => 6,
                'status' => 1,
            ],
            [
                'email' => 'chihiro.inoue@example.com',
                'title' => 'HTML/CSSコーディングを朝に進める作業会',
                'body' => 'コーディング作業を朝に進めたいです。WordPress実装や静的コーディング、フロント周りの作業をしている方と一緒に黙々作業できると嬉しいです。',
                'purpose' => '黙々作業',
                'location_type' => 'online',
                'meeting_tool' => 'Google Meet',
                'prefecture' => '千葉県',
                'start_at' => Carbon::now()->addDays(2)->setTime(8, 30),
                'end_at' => Carbon::now()->addDays(2)->setTime(10, 30),
                'time_zone' => 'morning',
                'max_participants' => 3,
                'status' => 1,
            ],
            [
                'email' => 'ryo.morita@example.com',
                'title' => 'Flutter個人開発の進捗共有作業会',
                'body' => 'Flutterでアプリを作っています。個人開発は継続が難しいので、作業開始時に今日やることを共有して、最後に進捗を共有する形で進めたいです。',
                'purpose' => '個人開発',
                'location_type' => 'online',
                'meeting_tool' => 'Discord',
                'prefecture' => '静岡県',
                'start_at' => Carbon::now()->addDays(5)->setTime(21, 0),
                'end_at' => Carbon::now()->addDays(5)->setTime(23, 0),
                'time_zone' => 'night',
                'max_participants' => 4,
                'status' => 1,
            ],
            [
                'email' => 'hana.shimizu@example.com',
                'title' => 'イラスト制作を一緒に進める午後の黙々会',
                'body' => 'SNSアイコンやWeb用イラストの制作を進めます。制作系の方、デザイン系の方、午後に集中して作業したい方を募集します。',
                'purpose' => '制作仲間探し',
                'location_type' => 'online',
                'meeting_tool' => 'Zoom',
                'prefecture' => '長野県',
                'start_at' => Carbon::now()->addDays(4)->setTime(13, 0),
                'end_at' => Carbon::now()->addDays(4)->setTime(15, 30),
                'time_zone' => 'daytime',
                'max_participants' => 5,
                'status' => 1,
            ],
            [
                'email' => 'ryo.hashimoto@example.com',
                'title' => '休日にLaravelとSQLの勉強を一緒にしたいです',
                'body' => '休日にLaravelとSQLの学習時間を取りたいです。業務システム開発やWeb開発の勉強をしている方と、ゆるく作業・学習できればと思っています。',
                'purpose' => '勉強',
                'location_type' => 'online',
                'meeting_tool' => 'Google Meet',
                'prefecture' => '広島県',
                'start_at' => Carbon::now()->addDays(6)->setTime(9, 30),
                'end_at' => Carbon::now()->addDays(6)->setTime(12, 0),
                'time_zone' => 'morning',
                'max_participants' => 4,
                'status' => 1,
            ],
            [
                'email' => 'risa.okada@example.com',
                'title' => '資料作成や業務改善タスクを夜に進める会',
                'body' => 'SaaS関連の資料作成や業務改善タスクを進めます。平日夜に1〜2時間だけでも集中して作業したい方と一緒にできると嬉しいです。',
                'purpose' => '黙々作業',
                'location_type' => 'online',
                'meeting_tool' => 'Zoom',
                'prefecture' => '沖縄県',
                'start_at' => Carbon::now()->addDays(3)->setTime(20, 30),
                'end_at' => Carbon::now()->addDays(3)->setTime(22, 0),
                'time_zone' => 'night',
                'max_participants' => 5,
                'status' => 1,
            ],
            [
                'email' => 'kazuya.fujita@example.com',
                'title' => 'SQL・Python分析作業を午前中に進めたいです',
                'body' => 'データ集計やダッシュボード作成を進めています。SQLやPythonで分析作業をしている方、または資料作成をしたい方と一緒に作業したいです。',
                'purpose' => '黙々作業',
                'location_type' => 'online',
                'meeting_tool' => 'Google Meet',
                'prefecture' => '東京都',
                'start_at' => Carbon::now()->addDays(2)->setTime(9, 0),
                'end_at' => Carbon::now()->addDays(2)->setTime(11, 0),
                'time_zone' => 'morning',
                'max_participants' => 4,
                'status' => 1,
            ],
            [
                'email' => 'anna.ishikawa@example.com',
                'title' => '教材作成・プログラミング学習の作業会',
                'body' => 'オンライン講師として教材作成を進めています。プログラミング学習中の方や、教材・資料作成をしたい方と一緒に作業できると嬉しいです。',
                'purpose' => '勉強',
                'location_type' => 'online',
                'meeting_tool' => 'Zoom',
                'prefecture' => '京都府',
                'start_at' => Carbon::now()->addDays(5)->setTime(14, 0),
                'end_at' => Carbon::now()->addDays(5)->setTime(16, 0),
                'time_zone' => 'daytime',
                'max_participants' => 6,
                'status' => 1,
            ],
            [
                'email' => 'makoto.hasegawa@example.com',
                'title' => '朝のタスク整理と集中作業を習慣化したい方募集',
                'body' => '朝にタスク整理をして、そのまま集中作業する時間を作りたいです。PM、ディレクター、エンジニア、ライターなど職種は問いません。作業習慣を作りたい方と一緒に続けたいです。',
                'purpose' => '作業習慣化',
                'location_type' => 'online',
                'meeting_tool' => 'Google Meet',
                'prefecture' => '大阪府',
                'start_at' => Carbon::now()->addDays(1)->setTime(7, 30),
                'end_at' => Carbon::now()->addDays(1)->setTime(9, 0),
                'time_zone' => 'morning',
                'max_participants' => 6,
                'status' => 1,
            ],
            [
                'email' => 'riko.murakami@example.com',
                'title' => '午前中に事務作業を片付ける黙々会',
                'body' => '請求書作成、メール返信、タスク整理などの事務作業を午前中にまとめて進めたいです。オンライン秘書、事務、フリーランスの方と一緒に作業できると嬉しいです。',
                'purpose' => '黙々作業',
                'location_type' => 'online',
                'meeting_tool' => 'Zoom',
                'prefecture' => '奈良県',
                'start_at' => Carbon::now()->addDays(4)->setTime(9, 30),
                'end_at' => Carbon::now()->addDays(4)->setTime(11, 30),
                'time_zone' => 'morning',
                'max_participants' => 5,
                'status' => 1,
            ],
            [
                'email' => 'naoki.kato@example.com',
                'title' => '奈良周辺で個人開発・作業できる方を探しています',
                'body' => '普段はリモートで作業していますが、たまに同じ空間で作業できる人がいると集中できると思っています。奈良周辺でコワーキングスペースやカフェ作業に興味がある方がいればつながりたいです。',
                'purpose' => '作業仲間探し',
                'location_type' => 'both',
                'meeting_tool' => 'Google Meet',
                'prefecture' => '奈良県',
                'start_at' => Carbon::now()->addDays(8)->setTime(13, 0),
                'end_at' => Carbon::now()->addDays(8)->setTime(16, 0),
                'time_zone' => 'daytime',
                'max_participants' => 3,
                'status' => 1,
            ],
            [
                'email' => 'riko.murakami@example.com',
                'title' => '奈良県内で午前中にカフェ作業できる方',
                'body' => '午前中に事務作業やタスク整理をしたいです。オンラインでも大丈夫ですが、奈良県内でタイミングが合えばカフェ作業もできる方を探しています。',
                'purpose' => '黙々作業',
                'location_type' => 'both',
                'meeting_tool' => 'Zoom',
                'prefecture' => '奈良県',
                'start_at' => Carbon::now()->addDays(10)->setTime(10, 0),
                'end_at' => Carbon::now()->addDays(10)->setTime(12, 0),
                'time_zone' => 'morning',
                'max_participants' => 2,
                'status' => 1,
            ],
            [
                'email' => 'misaki.tanaka@example.com',
                'title' => '大阪でデザイン作業できる方、オンライン参加も歓迎です',
                'body' => '大阪周辺でカフェやコワーキングスペースで作業できる方を探しています。オンライン参加も歓迎です。デザイン、ライティング、開発など作業内容は問いません。',
                'purpose' => '作業仲間探し',
                'location_type' => 'both',
                'meeting_tool' => 'Zoom',
                'prefecture' => '大阪府',
                'start_at' => Carbon::now()->addDays(9)->setTime(14, 0),
                'end_at' => Carbon::now()->addDays(9)->setTime(17, 0),
                'time_zone' => 'daytime',
                'max_participants' => 4,
                'status' => 1,
            ],
            [
                'email' => 'kenta.sato@example.com',
                'title' => 'Laravelのエラー調査を一緒に進める短時間作業会',
                'body' => 'Laravelのエラー調査やテスト修正を進めます。最初に詰まっている内容を軽く共有して、その後は黙々作業する形です。技術相談も少しできれば嬉しいです。',
                'purpose' => '技術相談',
                'location_type' => 'online',
                'meeting_tool' => 'Google Meet',
                'prefecture' => '東京都',
                'start_at' => Carbon::now()->addDays(6)->setTime(20, 0),
                'end_at' => Carbon::now()->addDays(6)->setTime(21, 30),
                'time_zone' => 'night',
                'max_participants' => 3,
                'status' => 1,
            ],
        ];

        foreach ($posts as $postData) {
            $email = $postData['email'];
            unset($postData['email']);
        
            $user = User::where('email', $email)->first();
        
            if (! $user) {
                continue;
            }
        
            // prefecture（都道府県名）を prefecture_id に変換する
            $prefectureName = $postData['prefecture'] ?? null;
            unset($postData['prefecture']);
        
            $postData['prefecture_id'] = $prefectureName
                ? Prefecture::where('name', $prefectureName)->value('id')
                : null;
        
            WorkPost::updateOrCreate(
                [
                    'user_id' => $user->id,
                    'title' => $postData['title'],
                ],
                [
                    ...$postData,
                    'user_id' => $user->id,
                ]
            );
        }
    }
}
